## Intro to Numpy

In [2]:
import numpy as np
import random
a =np.array([random.randint(0,21) for i in range(10)])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[11 13 11 15  2  1  6 19 13  9]


In [13]:
a1 = np.array([[[1,0,1,0],[1,1,1,0],[0,0,0,1]], [[1,1,1,0],[1,0,0,0],[1,0,0,1]]])
print(a1.shape)
print(a1.size)
print(a1.dtype)
print(type(a1))

(2, 3, 4)
24
int32
<class 'numpy.ndarray'>


In [16]:
import pandas as pd
df = pd.DataFrame(a1[1])
#if there are three dimensions, you will have to select a single object for display in a pandas DataFrame
df

0  1  2  3
0  1  1  1  0
1  1  0  0  0
2  1  0  0  1

## Creating Numpy Arrays

In [22]:
auto_array = np.ones((3))
print('1\n', auto_array)
auto_array2 = np.ones((3,3))
print('2\n', auto_array2)
auto_array3 = np.ones((3,3,3))
print('3\n', auto_array3)

1
 [1. 1. 1.]
2
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [28]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_step = np.arange(0,100,7)
range_step

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [29]:
random_array = np.random.randint(0,100, size=(2,5))
random_array

array([[59,  7, 79, 18, 33],
       [22, 83, 43, 70, 28]])

## Random Seed
Reproducible psuedo-random numbers

In [37]:
np.random.seed(seed=0)
random2 = np.random.randint(0,10, size=(7,5))
random2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3]])

In [39]:
np.random.seed(seed=7)
random3 =np.random.random((7,5))
random3

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837],
       [0.13316945, 0.52341258, 0.75040986, 0.66901324, 0.46775286],
       [0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039]])

In [41]:
np.random.seed(seed=7)
random4 =np.random.random((1,5))
random4

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951]])

## Viewing Arrays and Matrices

In [43]:
np.unique(random2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
auto_array[0]

1.0

In [45]:
auto_array2[0]

array([1., 1., 1.])

In [46]:
auto_array3[0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
auto_array3[-1:,-1:,-1:]

array([[[1.]]])

In [53]:
#make a big array 
big_array = np.random.randint(0,10,size=(2,3,4,5))
big_array

array([[[[7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4],
         [0, 3, 5, 6, 4]],

        [[0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2],
         [3, 1, 1, 8, 4]],

        [[2, 1, 7, 0, 8],
         [8, 1, 2, 3, 0],
         [1, 1, 5, 5, 6],
         [0, 9, 3, 2, 4]]],


       [[[2, 8, 4, 9, 0],
         [0, 2, 6, 3, 9],
         [5, 4, 6, 9, 9],
         [9, 4, 8, 2, 4]],

        [[6, 5, 3, 5, 2],
         [6, 4, 3, 2, 5],
         [9, 7, 5, 8, 5],
         [2, 0, 9, 3, 2]],

        [[2, 4, 3, 4, 8],
         [7, 0, 2, 7, 8],
         [8, 4, 0, 4, 1],
         [7, 4, 9, 0, 1]]]])

In [54]:
#get all 5 values of the first 1st-dimensional unit from the last 2nd-dimensional unit
big_array[-1:,-1:,0,:]

array([[[2, 4, 3, 4, 8]]])