# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1= np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(a1.ndim, a1.dtype, a1.size, type(a1))

1 int32 3 <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
print(a2.ndim, a2.dtype, a2.size, type(a2))

2 int32 18 <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
print(a3.ndim, a3.dtype, a3.size, type(a3))

3 int32 36 <class 'numpy.ndarray'>


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(data =a2)
df

0  1  2
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3
4  1  2  3
5  1  2  3

In [10]:
# Create an array of shape (10, 2) with only ones
o_array = np.ones((10,2))
o_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
z_array = np.zeros((7,2,3))
z_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,7)
range_array

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
r_array = np.random.randint(0,10, size=(7,2))
r_array

array([[8, 2],
       [6, 8],
       [4, 7],
       [2, 4],
       [1, 8],
       [9, 3],
       [9, 5]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rf_array = np.random.random((3,5))
rf_array

array([[0.19864097, 0.90531304, 0.57020356, 0.00100163, 0.41676194],
       [0.11884175, 0.3279517 , 0.1153877 , 0.58720727, 0.51602637],
       [0.53117171, 0.51388724, 0.85408401, 0.12246658, 0.96736815]])

In [21]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
r_a1 = np.random.randint(0,10,size=(4,6))
r_a1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r_a2 = np.random.randint(0,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(r_a2)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [23]:
# Find the 0'th index of the latest array you created
r_a2[0]

array([8, 0, 9, 2, 6, 3, 8])

In [25]:
# Get the first 2 rows of latest array you created
r_a2[0:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [26]:
# Get the first 2 values of the first 2 rows of the latest array
r_a2[:2,:2]

array([[8, 0],
       [2, 4]])

In [28]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
testa1 = np.random.randint(0,10,size=(3,5))
testa2 = np.ones((3,5))

In [33]:
# Add the two arrays together
sum_array = testa1+testa2
sum_array

In [34]:
# Create another array of ones of shape (5, 3)
testa3 = np.ones((5,3))
testa3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# Try add the array of ones and the other most recent array together
testa3+sum_array

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?


The shapes of each array are not aligned

How would you fix it?

You need to transpose the second array you want to add

In [36]:
# Create another array of ones of shape (3, 5)
new_array = testa3.T

In [37]:
# Subtract the new array of ones from the other most recent array
sum_array - new_array


array([[3., 5., 1., 9., 1.],
       [9., 3., 7., 6., 8.],
       [7., 4., 1., 4., 7.]])

In [40]:
# Multiply the ones array with the latest array
sum_array * new_array

array([[ 4.,  6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.,  9.],
       [ 8.,  5.,  2.,  5.,  8.]])

In [41]:
# Take the latest array to the power of 2 using '**'
sum_array **2

array([[ 16.,  36.,   4., 100.,   4.],
       [100.,  16.,  64.,  49.,  81.],
       [ 64.,  25.,   4.,  25.,  64.]])

In [42]:
# Do the same thing with np.square()
np.square(sum_array)

array([[ 16.,  36.,   4., 100.,   4.],
       [100.,  16.,  64.,  49.,  81.],
       [ 64.,  25.,   4.,  25.,  64.]])

In [43]:
# Find the mean of the latest array using np.mean()
np.mean(sum_array)

6.0

In [44]:
# Find the maximum of the latest array using np.max()
np.max(sum_array)

10.0

In [45]:
# Find the minimum of the latest array using np.min()
np.min(sum_array)

2.0

In [46]:
# Find the standard deviation of the latest array
np.std(sum_array)

2.7325202042558927

In [47]:
# Find the variance of the latest array
np.var(sum_array)

7.466666666666667

In [48]:
# Reshape the latest array to (3, 5, 1)
sum_array.reshape(3,5,1)

array([[[ 4.],
        [ 6.],
        [ 2.],
        [10.],
        [ 2.]],

       [[10.],
        [ 4.],
        [ 8.],
        [ 7.],
        [ 9.]],

       [[ 8.],
        [ 5.],
        [ 2.],
        [ 5.],
        [ 8.]]])

In [49]:
# Transpose the latest array
sum_array.T

array([[ 4., 10.,  8.],
       [ 6.,  4.,  5.],
       [ 2.,  8.,  2.],
       [10.,  7.,  5.],
       [ 2.,  9.,  8.]])

What does the transpose do?

Transpose reverses the order of the elements of an array. The last element of the last row would become the first element of the first row.

In [51]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
dot1 = np.random.randint(0,10,size=(3,3))
dot2 = np.random.randint(0,10,size=(3,2))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(dot1,dot2)

array([[135,  79],
       [ 58,  12],
       [ 70,  56]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat1 = np.random.randint(0,10,size=(4,3))
mat2 = np.random.randint(0,10,size=(4,3))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

It array shapes are not aligned; the inner shape information need to match (3==3). We can easily transpose the second array to solve this

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat1, mat2.T)

array([[ 40,  36,  10,  12],
       [153, 111,  57,  60],
       [140, 100,  52,  56],
       [ 48,  30,  37,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?
the inner shape information need to match (3rows for array 1==3columns for array 2). This is because the rows in array 1 are multiplied by the columns in array two then summed. but each row element need to be multiplied in array 1, thus the matching number.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [59]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0,10,size=(4,9))
arr2 = np.random.randint(0,10,size=(4,9))

In [60]:
# Compare the two arrays with '>'
arr1>arr2

array([[False, False, False,  True,  True, False, False,  True,  True],
       [False,  True,  True,  True, False, False, False,  True, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False,  True, False, False, False, False,  True, False]])

What happens when you compare the arrays with `>`?

It returns a set of booleans evaluating comparison operator element wise

In [61]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False, False,  True,  True,  True, False, False,  True,  True],
       [ True,  True,  True,  True, False, False,  True,  True, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False,  True, False, False, False, False,  True, False]])

In [62]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[False, False, False, False,  True, False, False, False,  True],
       [False, False, False,  True, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [63]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False,  True, False, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [64]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[0, 2, 2, 4, 5, 6, 7, 8, 9],
       [0, 0, 3, 3, 5, 7, 7, 8, 9],
       [0, 0, 0, 0, 1, 2, 4, 6, 7],
       [0, 0, 1, 1, 1, 2, 4, 5, 6]])

In [65]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([[6, 0, 7, 5, 2, 1, 3, 4, 8],
       [5, 6, 4, 8, 1, 0, 2, 3, 7],
       [3, 5, 7, 8, 1, 2, 4, 0, 6],
       [5, 6, 0, 1, 8, 7, 4, 2, 3]], dtype=int64)

In [66]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)

8

In [67]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

6

In [68]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([8, 7, 6, 3], dtype=int64)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)

In [72]:
# Create an array of normally distributed random numbers
np.random.normal(10, 3, size=(3,7))

array([[ 7.13650821,  7.74646173,  6.60871584, 12.30993208, 13.80516857,
        11.27345873, 12.82160675],
       [ 7.39707673, 10.43758556,  5.89038683,  7.68465775, 12.63602064,
         9.28121648, 13.62814591],
       [11.61388001, 18.20326648, 10.28129629,  5.7807842 ,  9.89641103,
         7.11095312, 12.93154   ]])

In [70]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.